name: Lottery
version: 1.0.0
main: hazardteam\lottery\Main
api: 5.3.0
author: HazardTeam
permissions:
  lottery.command:
    default: true
  lottery.command.play:
    default: true
  lottery.command.reload:
    default: op
