# Lottery Configuration

# Economy settings.
# Possible providers: economyapi, bedrockeconomy, xp
economy:
  provider: BedrockEconomy

# If you are using the "xp" provider, 1 unit = 1 level of experience.
min-bet: 1000

# minRange and maxRange must be a string and numeric
# chance must be an integer
range:
  - minRange: '-2.00'
    maxRange: '0.00'
    chance: 70
  - minRange: '0.00'
    maxRange: '2.00'
    chance: 40
  - minRange: '2.01'
    maxRange: '5.00'
    chance: 10 # Higher multiplier, lower chance
  - minRange: '-5.00'
    maxRange: '-2.01'
    chance: 5 # Higher loss, very low chance

messages:
  transaction-failed: '§e| §cTransaction failed. Please try again later or contact an admin if the issue persists.'
  invalid-bet: "§e| §7Your bet must be a number."
  receive-prize: "§e| §aYou won. Profit  §a{prize}"
  receive-less-prize: "§e| §cYou lost. Loss  §c{prize}. §7Still better than a bigger loss."
  loss-prize: "§e| §cYou lost. Loss  §c{prize}"
  no-enough-money: "§e| §7You do not have enough money to place a bet."
  less-than-min-bet: "§e| §7Your bet is too small."
  broadcast-message: "§7[§6GAMBLING§7] §a{player} §fplaced a bet of §a{bet}. §fWin/Loss §e{earn}. §fTotal earned §6{prize} §fwith §6{calculation} §fcalculation."
  break-even-prize: "§e| §7You broke even. No loss, no gain."
  reload-success: "§e| §aLottery plugin reloaded successfully!"

forms:
  play:
    title: "§7-= §eLOTTERY §7=-"
    content: "§6» §fYour balance:  §a{money}"

gui:
  lottery:
    title: "§7-= §eLOTTERY JACKPOT §7=-"
    items:
      reveal: "§aPreview Result"
      bet-info: "§eYour Bet:  §a{bet}"
  reveal:
    title: "§7-= §eRESULTS §7=-"
    items:
      reveal-result: "§aMove this to see the Result"
