# Lottery Configuration

# Economy settings.
# Possible providers: economyapi, bedrockeconomy, xp
economy:
  provider: BedrockEconomy

# If you are using the "xp" provider, 1 unit = 1 level of experience.
min-bet: 1000

range:
  -2.00=0.00: 70
  0.00=2.00: 40

messages:
  transaction-failed: '§e| §cTransaction failed. Please try again later or contact an admin if the issue persists.'
  invalid-bet: "§e| §7Your bet must be a number."
  receive-prize: "§e| §aYou won. Profit §b §a{prize}"
  receive-less-prize: "§e| §cYou lost. Loss §b §c{prize}. §7Still better than a bigger loss."
  loss-prize: "§e| §cYou lost. Loss §b §c{prize}"
  no-enough-money: "§e| §7You do not have enough money to place a bet."
  less-than-min-bet: "§e| §7Your bet is too small."
  broadcast-message: "§7[§6GAMBLING§7] §a{player} §fplaced a bet of §a{bet}. §fWin/Loss §e{loss}. §fTotal earned §6{prize} with §6{calculation} calculation "

forms:
  play:
    title: "§7-= §eLOTTERY §7=-"
    content: "§6» §fYour balance: §b §a{money}"

gui:
  lottery:
    title: "§7-= §eLOTTERY JACKPOT §7=-"
    items:
      reveal: "§aPreview Result"
      bet-info: "§eYour Bet: §b §a{bet}"
  reveal:
    title: "§7-= §eRESULTS §7=-"
    items:
      reveal-result: "§aMove this to see the Result"
