min-bet: 1000

range:
  -2.0=0.0: 70
  0.0=2.0: 40

messages:
  invalid-bet: "§e| §7Your bet must be a number."
  receive-price: "§e| §aYou won. Profit §b §a{price}"
  receive-less-price: "§e| §cYou lost. Loss §b §c{price}. §7Still better than a bigger loss."
  loss-price: "§e| §cYou lost. Loss §b §c{price}"
  no-enough-money: "§e| §7You do not have enough money to place a bet."
  less-than-min-bet: "§e| §7Your bet is too small."
  broadcast-message: "§7[§6GAMBLING§7] §a{player} §fplaced a bet of §a{bet}. §fWin/Loss §e{loss}. §fTotal earned §6{price}"

forms:
  play:
    title: "§7-= §eLOTTERY §7=-"
    content: "§6» §fYour balance: §b §a{money}"

gui:
  lottery:
    title: "§7-= §eLOTTERY JACKPOT §7=-"
    items:
      reveal: "§aPreview Result"
      bet-info: "§eYour Bet: §b §a{bet}"
  reveal:
    title: "§7-= §eRESULTS §7=-"
    items:
      reveal-result: "§aMove this to see the Result"
